apiVersion: v1
kind: Service
metadata:
  name: egresshttpbin
  namespace: istio-tutorial
  labels:
    app: egresshttpbin    
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: egresshttpbin
